### ISSUE TITLE
https://ffnord.net bitte nicht benutzen

### ISSUE THREAD

**Issue by rubo77** [Freifunk-Nord/nord-community-api#1]
Wir sollten überall die hauptdomain nord.freifunk.net benutzen, da dies unsere ssid ist.

außerdem denke ich es sit sinnvoller dieses repo wieder zu löschen und die api auf dem services rechner oder einem gateway zu generieren und automatisch mit der aktuellen anzahl nodes zu updaten

**Comment by Tarnatos** [comment]
Zustimmung!
