### ISSUE TITLE
Dokumentation?

### ISSUE THREAD

**Issue by MTRNord** [Freifunk-Nord/nord-community-api#5]
Würde gerne wissen welche geo koordianten ins Script müssen :) dann kann ich Tarp nachtragen

**Comment by Tarnatos** [comment]
Bitte in https://github.com/Freifunk-Nord/nord-community-api/pull/4 diskutieren.

**Comment by 4ndr3** [comment]
Jetzt nirgendswo mehr. Ursprünglich hatte ich das Skript so, dass es eine Originaldatei gab und alle Anpassungen der Landkreise in der Variable Landkreise definiert wurden. Da dann alles umgebaut wurde und jeder Landkreis handangepasst wurde, habe ich dass alles rausgeworfen und editiere jetzt nur noch die Knotenzahl und das Datum.
